# dynamic_conf.yml — Development
tls:
  certificates:
    - certFile: "/etc/traefik/certs/odoo_app_crt.pem"
      keyFile:  "/etc/traefik/certs/odoo_app_key.pem"
http:

  # 1) Dashboard router — only on websecure, only from localhost
  routers:
    
    # Odoo-Service router
    odoo-router:
      entryPoints:
        - api
      rule: "PathPrefix(`/`)"
      service: odoo-service
    #  tls: {}

    # HwProxy Service router
    hw-proxy-router:
      entryPoints:
        - hw
      rule: "PathPrefix(`/hw_status`)"
      service: hw-proxy-service
    #  tls: {}

  services:
    odoo-service:
      loadBalancer:
        servers:
          - url: "http://fiesta_odoo:8069"
    hw-proxy-service:
      loadBalancer:
        servers:
          - url: "http://hw_status_service:8015"

  middlewares:
    ip-allowlist:
      IPAllowList:
        # Only allow dashboard from the Docker host itself
        sourceRange:
          - "127.0.0.1/32"
          - "::1/128"